export const tableConfig = {
    filterable: true,
    className: '-striped',
    defaultPageSize: 10,
    previousText: '<',
    nextText: '>',
    loadingText: 'Cargando',
    noDataText: 'Sin datos',
    pageText: '',
    ofText: 'de',
    rowsText: 'registros',
    pageSizeOptions: [10, 20, 25, 50, 100],
};

export const dummyData = [
    {
        string1: 'AAA',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 21,
        date: 'fjsadklj',
    },
    {
        string1: 'BBB',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 26,
        date: 'fjsadklj',
    },
    {
        string1: 'CCCC',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 36,
        date: 'fjsadklj',
    },
    {
        string1: 'AAA',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 21,
        date: 'fjsadklj',
    },
    {
        string1: 'BBB',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 26,
        date: 'fjsadklj',
    },
    {
        string1: 'CCCC',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 36,
        date: 'fjsadklj',
    },
    {
        string1: 'AAA',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 21,
        date: 'fjsadklj',
    },
    {
        string1: 'BBB',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 26,
        date: 'fjsadklj',
    },
    {
        string1: 'CCCC',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 36,
        date: 'fjsadklj',
    },
    {
        string1: 'AAA',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 21,
        date: 'fjsadklj',
    },
    {
        string1: 'BBB',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 26,
        date: 'fjsadklj',
    },
    {
        string1: 'CCCC',
        string2: 'Test',
        string3: 'fkalsdaf',
        string4: 'falksdj',
        number: 36,
        date: 'fjsadklj',
    },
];
